name: example
description: A playground for the UI kit developed for the FitnestX App
version: 0.0.1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fitx_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
